✨✏️ Removed .env from .gitignore
VoloBuilds/openai-assistants-discord-bot pull request #1
Opened 2023-11-12 13:53 UTC by ShivamB25

2023-11-12 13:53 UTC, ShivamB25 reviewed
bot.js can be probably improved.

2023-11-12 16:14 UTC, VoloBuilds commented
Hey @ShivamB25!! Thanks for the PR! Just wanted you to know I saw it and I will review later today :)

2023-11-13 04:10 UTC, VoloBuilds requested changes
Thank you for the PR! Really appreciate the Docker additions and the .env change is good too. Left comments; let me know if you can make the changes so I can merge!

2023-11-13 04:10 UTC, VoloBuilds commented on .env.sample
This is a good idea, thanks

2023-11-13 04:10 UTC, VoloBuilds commented on .gitignore
Could you reduce the .gitignore back down to only reasonable stuff for this repo? All of those extra ignores add bloat to the repo and may confuse users as to why they are included. Let's just have node_modules and .env in the gitignore (which I think was your main goal anyway)

2023-11-13 04:10 UTC, VoloBuilds commented on Dockerfile
Great! Thank you for this

2023-11-13 04:10 UTC, VoloBuilds commented on README.md
> +   mv .env.sample .env
👍

2023-11-13 04:10 UTC, VoloBuilds commented on bot.js
Let's keep the original 4-spaces style; please revert the changes to bot.js. Feel free to use 2-space in your fork if you wish!

2023-11-15 08:06 UTC, ShivamB25 reviewed
ok

2023-11-15 08:06 UTC, ShivamB25 reviewed
test

2023-11-15 16:26 UTC, VoloBuilds approved these changes
Fantastic, thanks @ShivamB25! Merging

2023-11-15 16:27 UTC, merged